version: 2.1

jobs:
  test-and-compile-front-end:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Compile Extension
          command: npm run compile:extension
      - run:
          name: Compile Views
          command: npm run compile:views
      - run:
          name: Run Tests
          command: npm run jestTest
      - store_test_results:
          path: test-results/jest
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Install vsce
          command: npm install vsce --legacy-peer-deps
      - run:
          name: Build Extension
          command: npm run vsce
workflows:
  build:
    jobs:
      - test-and-compile-front-end
      - build
